# PlanetaryPy Index URLs Configuration

# This file contains URLs for PDS indices, organized by mission and instrument


[missions]
# # Mro Mission

[missions.mro]
# # CTX Instrument

[missions.mro.ctx]
edr = "https://planetarydata.jpl.nasa.gov/img/data/mro/ctx/mrox_5010//index/cumindex.lbl"

# # Latest URL discovered on 2025-03-07

# # HIRISE Instrument

[missions.mro.hirise]
dtm = "https://hirise-pds.lpl.arizona.edu/PDS/INDEX/DTMCUMINDEX.LBL"
edr = "https://hirise-pds.lpl.arizona.edu/PDS/INDEX/EDRCUMINDEX.LBL"
rdr = "https://hirise-pds.lpl.arizona.edu/PDS/INDEX/RDRCUMINDEX.LBL"
# # CRISM Instrument

[missions.mro.crism]
mtrdr = "https://pds-geosciences.wustl.edu/mro/mro-m-crism-5-rdr-mptargeted-v1/mrocr_4001/index/mtrdr0705_index.lbl"

# # Lro Mission

[missions.lro]
# # LROC Instrument

[missions.lro.lroc]
edr = "https://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0061C//INDEX/CUMINDEX.LBL"

# # Latest URL discovered on 2025-03-07

# # Latest URL discovered on 2025-03-07
# # DIVINER Instrument

[missions.lro.diviner]
edr1 = "https://pds-geosciences.wustl.edu/lro/lro-l-dlre-2-edr-v1/lrodlr_0001/index/index.lbl"
edr2 = "https://pds-geosciences.wustl.edu/lro/lro-l-dlre-2-edr-v1/lrodlr_0002/index/index.lbl"
rdr1 = "https://pds-geosciences.wustl.edu/lro/lro-l-dlre-4-rdr-v1/lrodlr_1001/index/rdrindex.lbl"
rdr2 = "https://pds-geosciences.wustl.edu/lro/lro-l-dlre-4-rdr-v1/lrodlr_1002/index/rdrindex.lbl"
# # LOLA Instrument

[missions.lro.lola]
edr = "http://pds-geosciences.wustl.edu/lro/lro-l-lola-2-edr-v1/lrolol_0xxx/index/edrindex.lbl"
rdr = "http://pds-geosciences.wustl.edu/lro/lro-l-lola-3-rdr-v1/lrolol_1xxx/index/rdrindex.lbl"

# # Cassini Mission

[missions.cassini]
# # ISS Instrument

[missions.cassini.iss]
index = "https://pds-rings.seti.org/holdings/metadata/COISS_2xxx/COISS_2999/COISS_2999_index.lbl"
inventory = "https://pds-rings.seti.org/holdings/metadata/COISS_2xxx/COISS_2999/COISS_2999_inventory.lbl"
moon_summary = "https://pds-rings.seti.org/holdings/metadata/COISS_2xxx/COISS_2999/COISS_2999_moon_summary.lbl"
ring_summary = "https://pds-rings.seti.org/holdings/metadata/COISS_2xxx/COISS_2999/COISS_2999_ring_summary.lbl"
saturn_summary = "https://pds-rings.seti.org/holdings/metadata/COISS_2xxx/COISS_2999/COISS_2999_saturn_summary.lbl"
# # UVIS Instrument

[missions.cassini.uvis]
index = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_index.lbl"
moon_summary = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_moon_summary.lbl"
ring_summary = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_ring_summary.lbl"
saturn_summary = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_saturn_summary.lbl"
supplemental_index = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_supplemental_index.lbl"
versions = "https://pds-rings.seti.org/holdings/metadata/COUVIS_0xxx/COUVIS_0999/COUVIS_0999_versions.lbl"

# # Go Mission

[missions.go]
# # SSI Instrument

[missions.go.ssi]
edr = "https://pds-rings.seti.org/holdings/metadata/GO_0xxx/GO_0999/GO_0999_index.lbl"
